### ISSUE TITLE
RPI 1209F : DOS parameter issues with OPTABLE and MACHINE options

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#100]
Raised by Abe Kornelis 2014/07/24
OPTABLE(xxx,[NO]LIST) and and MACHINE(xxx,[NO]LIST) get split by DOS parser when passed as direct parameter on the invocation command. Subsequently they are not recognized as valid parameters.

**Comment by z390org** [comment]
Please test whether enclosing the parm in double quotes resolves the issue

**Comment by abekornelis** [comment]
Adding double quotes around the entire option resolves the problem with the embedded comma.
Closing this issue. No action is needed.
