### ISSUE TITLE
RPI 1216: HLASM compatible OPTABLE and MACHINE options

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#104]
Raised by Abe Kornelis 2012/05/24
Create support for OPTABLE and MACHINE options, equivalent to HLASM.

**Comment by z390org** [comment]
Please double-check - we think it's already been done.

**Comment by abekornelis** [comment]
Optable and Machine options have been implemented long ago.
The opcode table has been broken down into segments to enable composing the selected opcode table from the relevant building blocks.
