### ISSUE TITLE
RPI 1508  : TEST() comment fixes

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#109]
Raised by Abe Kornelis 2015/01/28
Documented option TESTDD() is implemented as TEST() - Correct documentation. Also: explain that TEST() takes the name of a variable containing the command file path+name. Also: when end of command file is reached and program has not yet ended Quit command is generated

**Comment by adelosa** [comment]
So not sure about this one.. was this you @z390org? Here are the 2 options:

> TEST | E | NO | Start execution with interactive TEST mode active which prompts for commands such as T opcode or G opcode to trace or execution to the next occurrence of opcode name.
> TESTDD(file) | E | NO | Define input command file to run TEST commands.  See regression test rt\test\TESTTST1.MLC for example.

So are we saying that the TESTDD(x) option does not exist, it is just TEST(x)?
Suggested text to replace the above would be appreciated..

**Comment by z390org** [comment]
Yes, the extant doco does not match the code. Doco says TESTDD(file) whereas code reacts to TEST(ddname) 
The E indicates the option is used only in the emulator (that's correct) 
and the NO is from the default column. The default is correct too.

Apart from fixing the type I'd like to add text to the extent that ddname is the name of a host environment variable holding the actual path and name of the file to be used as input command stream.
