### ISSUE TITLE
RPI 1519  : GPL license

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#113]
Raised by Abe Kornelis 
Include a proper copy of the GPL license with the distributed code

**Comment by z390org** [comment]
Should be in the doc subdirectory. Please double check whether the correct version is included.

**Comment by adelosa** [comment]
So, in terms of licenses, are we targeting GPL v3?  If so, the following page details what is required to make your app GPL v3 - https://www.gnu.org/licenses/gpl-3.0.en.html

In summary - each program source should have the following included at the start:

    z390 - Mainframe assembler emulator and run-time engine
    Copyright (C) 2021 Don Higgins

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

For any command line interfaces, when they start in interactive mode provide the following message:

    z390 Copyright (C) 2021 Don Higgins
    This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
    This is free software, and you are welcome to redistribute it
    under certain conditions; type `show c' for details.

This could just be part of a version command that returns the version and the license details.

I have already mentioned in #236 that we also need contributors to agree to assign copyright to Don as part of their contributions. This assumes that has happened, otherwise they would put their name instead of Dons.
