### ISSUE TITLE
RPI 1578: Doco missing details for .CPZ

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#155]
Raised by Abe Kornelis 2016/03/30
doco page on options and file type conventions misses .CPZ for zCobol copy books

**Comment by adelosa** [comment]
@z390org  - If you provide me a format, file description and file or Report format description, I will add this file type to the zCOBOL doco. Let me know if you need more details.. I just have no idea what this file type is for.

**Comment by z390org** [comment]
The .cpz file designates a cobol copy member as opposed to a .cpy which holds an assembler copy member. For example in the cics directory you will find DFHAID in both variants.

**Comment by jyganci** [comment]
Issue appears to be resolved in the markdown doc.
