### ISSUE TITLE
RPI 1581: BLDJAR6.BAT contains hardcoded Java path

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#157]
Raised by Martin Ward 2016/04/06
BLDJAR6.BAT contains hardcoded path for Java version 1.6.0_31; see mail by Martin Ward dd 2016-04-06 12:37

**Comment by z390org** [comment]
Email by Martin Ward:

I wrote the initial versions of the scripts to run under Linux.

To find the files, z390.pl looks in the following directories:

$HOME/lib/z390, /usr/local/lib/z390 and /usr/lib/z390

(where $HOME is your home directory)

It also looks in the directory in the environment variable Z390
if this variable is present.

It searches each of these directories in turn for the file z390.jar,
and expects the mac directory to be in the same directory.

cmd.pl and dos.pl can stay in the z390 directory and do not need
to be in your PATH.

dos.pl just calls cmd.pl which is an interpreter for a small
subset of batch file commands.

On 06/04/16 10:49, lists@openmailbox.org [z390] wrote:
> BLDJAR6.BAT
> Can't exec "if": No such file or directory at
/home/test/bin/z390/cmd.pl line 289.

This error indicates that cmd.pl could not interpret the IF syntax
in a batch file. File BLDJAR6.BAT looks OK (but I see that
it includes a hard coded path name and version number
for Java version 1.6.0_31: which is a very old version!)

To recompile z390.jar on Linux I use these commands:

cd ~/lib/z390/src
javac *.java
jar cmvf Z390.MAN z390.jar *.class
cp z390.jar ../z390.jar

The "cd" command enters the source directory under the main
z390 directory.

-- 
Martin

**Comment by adelosa** [comment]
There has been substantial work done on the batch scripts as part of the build automation and deprecation of the perl unix interface. Closing this as I don't think this is relevant anymore. If you have issues with the current scripts, either bash or bat, please raise a new issue.
