### ISSUE TITLE
RPI 1588: noasm does not recognise opcodes and directives

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#164]
Raised by Abe Kornelis 2016/09/04
in noasm mode mz390 recognizes neither opcodes nor directives and treats them as macros

**Comment by dsh33782** [comment]
Note NOASM is for use in pure text processing programs which only use conditional macro code and AREAD/PUNCH with extensions to process ascii text files.  NOASM does not support ordinary symbol attribute tests, OPSYN, or lookahead mode, and requires CHKMAC(0) and CHKSRC(0-2).
Ref:  http://www.z390.org/z390_Options.htm
