### ISSUE TITLE
RPI 1615: REPRO and REPRO2 assembly fail VCLR mapping in VCDTD.mac

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#189]
Raised by Abe Kornelis 2018/03/25
In Linklib, modules REPRO and REPRO2 fail to assemble due to mismatches with VCLR mapping in VCDTD.mac

**Comment by z390org** [comment]
Comment by Melvyn Maltz:

A brief run through [the issue] list showed up RPI1615, I don't think this problem exists, or ever did...if you have reason to think it's still a problem, let me know and I'll fix it, otherwise close it
