### ISSUE TITLE
RPI 1630: unix based system parameter string doco

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#202]
Raised by Hugh Sweeney 2019/02/11
Provide doco that on *ix systems the parameter string may need escaping when parentheses are used. See mail by Hugh Sweeney dd 2019-02-11 10:20

**Comment by z390org** [comment]
Email by Hugh Sweeney:



On Sun, 10 Feb 2019 at 20:45, Abe Kornelis <abe@bixoft.nl> wrote:

    Hugh,

    Thanks for the info. I'll create an RPI to make sure we'll update the doco.

    Would you happen to know whether the double quotes are required for each option,
    or for the option string as a complete entity?

    In other words: would you code "zvsam(1) allow"
    or would you code "zvsam(1)" "allow"

It's just the parentheses that cause the problem. Here's an example:

    hsweeney@ugo-AO531h:~$ echo java ez390 /x/y/z/myPgm.390 zVSAM(2) allow
    bash: syntax error near unexpected token `('
    hsweeney@ugo-AO531h:~$

The error is detected in bash, the Linux shell, long before the command line gets executed. Parentheses need to be escaped. Here's an explanation: https://unix.stackexchange.com/questions/26063/how-are-parentheses-interpreted-at-the-command-line . So, it's a problem only for those Linux users, like me, who are not alert to the meaning given to every last punctuation mark in bash. My workaround was lucky not to trip over another rule. I now believe that zVSAM\(2\) would be the safest formulation. But it's so general that I think it's only worth the vaguest remark in the docs, eg "Linux users may need to escape certain characters, such as parentheses, in entering commands". In relation to all commands, not just this one.

Hugh
--

**Comment by adelosa** [comment]
I don't think this is a doco issue although the problem could be documented and left unfixed.

Ideally I think that standard parameter passing should be used. I.e. don't have parameters with brackets.

Now I know this would make the parameters different from what is done on the mainframe but its NOT on the mainframe.
Normal parameters are passed for Windows and *nix type shells via - and -- type parameters. This is pretty standard and does not require quoting.

In this case, something like --vsam-version 2 would be the standard. 
I have raised this topic before and this is probably a project principal thing - Do we want to mirror mainframe things even when it causes issues off the mainframe or is not a natural pattern for off the mainframe. 

This leads to a different enhancement - start using a standard command line parser rather than creating our own. See https://picocli.info/ for an example library that provides standard CLI processing for Java apps.

Food for thought.. Happy to document this annoyance for Unix users even if it annoys them to no end (I am sure that @jyganci may have some views on this item)

**Comment by z390org** [comment]
@adelosa You raise a good point. To avoid breaking compatibility we'd need to support dual syntax. One version corresponding to what we already have, and another to support a more Unix-standard syntax. I think it should not be too hard - just a lot of work to enhance the tz390 module to support dual syntax for many parameters. Documenting the dual syntax and the drawbacks of using parentheses should be documented, including the option to circumvent by either using alternative syntax or using escape chararcters - at the user's discretion.

**Comment by hsweeney** [comment]
It's not a question of mainframe vs unix syntax. It's a question of what users prefer. I asked what users prefer but got no details.
Also bear in mind that the ``parmname(parmval)`` format was chosen because Windows had difficulties with the ``parmname=parmval`` format. Dunno what RPI. Probably DSH coded it.

**Comment by jyganci** [comment]
Yes, it's a pain remembering to type "zvsam(1)" or zvsam\(1\) but Linux/MacOS users should be made aware of the problem via something like Hugh's (intentionally vague) statement.
