### ISSUE TITLE
RPI 1634: Docs for zCICS regression testing

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#205]
Raised by Abe Kornelis 2019/04/12
Document how to perform regression test for zCics. See mail by Melvyn Maltz dd 2019-02-14 22:46

**Comment by z390org** [comment]
Comment by Melvyn Maltz:

I am not sure why RPI1634 was raised in the first place
zCICS SEQ support has been well documented for ages, as well as its use in the zCICS regression test
 
I'm happy for it to be closed
