### ISSUE TITLE
RPI 1642: Parameter doco issues

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#212]
Raised by Hugh Sweeney 2019/10/11
Doco request to specify that paths must not end in a plus sign. Also please use the term _appended to_ instead of _concatenated with_. See mail by Hugh Sweeney dd 2019-10-11 14:10

**Comment by z390org** [comment]
Email by Hugh:


On Sat, 17 Aug 2019 at 18:34, Abe Kornelis <abe@bixoft.nl> wrote:

    Hugh,

    The sysmac option can be specified multiple times.

    If the first character is a plus-symbol, it will append the path(s) to the existing path(s).
    It it does not start with a plus sign, it will replace the complete path-set with the new one.

    Your path ends in a plus sign, so the path-set is replaced with that,
    and I assume (danger!) that the path ending in a plus symbol does not exist.
    Therefore no macros will be found.
>

A very thorough analysis of my error, thank you Abe.

If I specify sysmac multiple times, like SYSMAC(ABLE) SYSMAC(BAKER) SYSMAC(CHARLIE)
will my datasets be concatenated in that order?

I made the mistake of ending my option with a plus sign, even though the documentation doesn't say that's allowed.
(Documentation change request: I find the phrase "concatenated with" slightly ambiguous. "Concatenated to" or better still "appended to" would more obviously convey the meaning intended. But hey, I'm not British, what do I know about English?)

And I think my original intention is not catered for:

    I thought I could just prefix my directory called MACv2 to whatever concatenation that the batch file was already using (without having to know what that is).

I think that that is a common requirement when exploring or tinkering in cases like this:

    I want to make an experimental tweak to say the ACB macro to derive some option from a GBLC set by some alien macro;
    I want to use one private macro in several assemblies; I want to place that ahead of z390 macros so that I don't have to manually verify that z390 doesn't have a macro of the same name.

I have found that facility helpful and time-saving on many projects in the past.

Hugh

**Comment by jyganci** [comment]
I believe that the markdown doc has resolved this issue.
