### ISSUE TITLE
RPI 2226: Change &sysvsam default to 2

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#227]
Raised by Melvyn Maltz 2020/12/28
Change &sysvsam default to 1

**Comment by dsh33782** [comment]
RPI 2226 change to tz390.java was made to set default to 1 in z390_v1704
I assume this is still open to change default to 2 when zVSAM2 is ready

**Comment by z390org** [comment]
It was intentional to have the value default to 1. At least until after zVSAM V2 is ready and has been stabilized sufficiently to deprecate the use zVSAM V1 and give all users ample opportunity to convert their datasets!
