### ISSUE TITLE
RPI 3001: OPEN/CLOSE parameter list zOPC

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#229]
Raised by Hugh Sweeney 2021/02/08
OPEN/CLOSE parameter list zOPC. See mail by Hugh Sweeney dd 2021-02-08 09:48.

**Comment by z390org** [comment]
From Hugh's mail:
I would like an RPI number please for "OPEN/CLOSE parameter list zOPC", last mentioned I think in your email of 2019-08-01 14:07. I have coded this major change to SZ390 but haven't succeeded in testing it. It's too unstable to include in handover/3 so I'm going to park it in a handover/4. I may or may not get around to finishing it. Also, Melvyn mentioned way back when I first was ill that he was going to go ahead and implement zVSAM V2 in Assembler, so my zOPC changes may be irrelevant. Most of my code changes outside of SZ390 are to do with z390 choosing to startup in V1 or V2 mode so should still stand. And, I contend, easier for a total newbie to learn from than the 1.5.06 code :-)

**Comment by z390org** [comment]
We need to create a mapping macro defining a DSECT for the Open/Close Parmlist. Abe has a macro to do that which we can reuse. Problem with the current solution is that an open/close request is expanded by the macro into a series of SVCs - one for each DCB/ACB. This approach blocks us from implementing open/close macros with MF=L and/or MF=E.

**Comment by z390org** [comment]
Here's the relevant section from my mapping macro:
~~I'm sorry - no fixed font available, and leading * for comment lines are shown as bullets :-(~~

```
OCPL     DSECT ,                       * MODE=24 version              
OC24     DS    0F                      * Each entry is an aligned word
OC24OPT  DS    XL1                     * Option byte: see below       
OC24DCB  DS    AL3                     * Pointer to DCB               
OC24_LEN EQU   *-OC24                                                 
*                                                                     
         ORG   OC24                    * MODE=31 version              
OC31     DS    0FL8                    * Two words on word boundary   
OC31OPT  DS    XL1                     * Option byte                  
OC31NULL DS    AL3                     * Contains zeroes              
OC31DCB  DS    AL4                     * Pointer to DCB               
OC31_LEN EQU   *-OC31                                                 
*                                                                     
* Following is a list of bit-definitions for the OPT byte:            
* See SYS1.MODGEN(IECEQU) for the official definitions                
*   End-of-list-indicator  BIT0                                       
*   2nd option=DISP        NOBITS (bits 1-3 off)                      
*   2nd option=REWIND      BIT1                                       
*   2nd option=FREE/IDLE   BIT2                                       
*   2nd option=REREAD      BIT3                                       
*   2nd option=LEAVE       BIT2+BIT3                                  
*   1st option=INPUT       NOBITS (bits 4-7 off)                      
*   1st option=RDBACK      BIT7                                       
*   1st option=UPDAT       BIT5                                       
*   1st option=INOUT       BIT6+BIT7                                  
*   1st option=OUTIN       BIT5+BIT6+BIT7                             
*   1st option=OUTINX      BIT5+BIT6                                  
*   1st option=EXTEND      BIT4+BIT5+BIT6                             
*   1st option=OUTPUT      BIT4+BIT5+BIT6+BIT7                        
```

**Comment by z390org** [comment]
Melvyn proposes to add a counter to the list indicating the number of entries. By using that counter we can prevent a MF=E expansion to exceed the area allocated by the corresponding MF=L expansion. To support this the invocation of open/close macros need not be changed, so source-level compatability can still be guaranteed.

**Comment by z390org** [comment]
Issue #250 covers remaining issues. Closing this issue.
