### ISSUE TITLE
Need to add NOTIME option to longer running BAT commands to prevent timeouts

### ISSUE THREAD

**Issue by dsh33782** [z390development/z390#235]
Some longer running BAT commands such as the new RUNRTQSAM.BAT which creates some larger QSAM test files and verifies them to test large block support may require the NOTIME option to prevent timeout errors on some systems with slower processors or disk subsystems.

**Comment by abekornelis** [comment]
@jyganci Would you please fix this in any scripts that run out of time?
(or see it as an argument to buy faster equipment ... )

**Comment by dsh33782** [comment]
I have reconsidered this and think it is better to not add NOTIME.  The default time limit catches programs that have gone into permanent loop.  If a bat command times out, try running it separately, and if it still fails, add NOTIME and monitor it and cancel it if it exceeds reasonable time.

**Comment by abekornelis** [comment]
I would suggest using a higher value for the TIME(nnn) option. NOTIME is truly unlimited. E.g. I use TIME(300) for a very large program. Just a thought - most of the time you'd rather have a high upper limit than  none at all ...
