### ISSUE TITLE
Missing error message during assembly

### ISSUE THREAD

**Issue by z390org** [z390development/z390#239]
Assembling the IIHF instruction with an undefined second operand does no longer produce an error message.
Melvyn is confident the message was issued correctly in V1.5.06, he thinks it still was correct in V1.7.05.
Yet in V1.7.06 the message no longer is issued. Please see attached sample. Melvyn has marked the missing error with a comment line.

**Comment by z390org** [comment]
15:40:36 SAMPLE3   MZ390 START USING z390 V1.7.06 ON J2SE 11.0.10 04/08/21
AZ390I Copyright 2021 Don Higgins
AZ390I z390 is licensed under GNU General Public License
AZ390I program = C:\MARVSE\Z390_10\PROGRAMS\SAMPLE3
AZ390I options = SYSMAC(C:\MARVSE\SOFTWARE\Z390\MAC)
External Symbol Definitions
 ESD=0001 LOC=00000000 LEN=00000090 TYPE=CST NAME=SAMPLE3
Assembler Listing
000000                                        (1/1)1 SAMPLE3  SUBENTRY 
000000                                       (2/78)2+SAMPLE3  CSECT 
000000 90ECD00C                             (2/168)3+         STM   14,12,12(13)
000004 45FF0068                             (2/169)4+         BAL   15,104(15)
000008 0000000000000000                     (2/170)5+         DC    18F'0'
000050 E2C1D4D7D3C5F340                     (2/171)6+         DC    CL8'SAMPLE3'
000058 F0F461F0F861F2F1                     (2/172)7+         DC    CL8'04/08/21'
000060 F1F54BF4F0404040                     (2/173)8+         DC    CL8'15.40'
000068 50FD0008                             (2/174)9+         ST    15,8(13)
00006C 50DF0004                            (2/175)10+         ST    13,4(15)
000070 18DF                                (2/176)11+         LR    13,15
000072                                     (2/189)12+         USING SAMPLE3+8,13
LISTUSE SAMPLE3  ESD=0001 LOC=00000008 LEN=01000 REG=D OFF=00000 LAB=
000072                                       (1/2)14 * MEL IS NOT DEFINED
000072 C0A8FFFFFFFF            FFFFFF        (1/3)15          IIHF  R10,MEL
000078                                       (1/4)16          SUBEXIT 
000078 41F00000                             (3/33)17+         LA    15,0
00007C 58D0D004                             (3/50)18+         L     13,4(,13)
000080 58E0D00C                             (3/51)19+         L     14,12(,13)
000084 982CD01C                             (3/52)20+         LM    2,12,28(13)
000088 07FE                                 (3/53)21+         BR    14
00008A                                       (1/5)23          YREGS 
00008A                  00000000             (4/3)24+R0       EQU   0
00008A                  00000001             (4/4)25+R1       EQU   1
00008A                  00000002             (4/5)26+R2       EQU   2
00008A                  00000003             (4/6)27+R3       EQU   3
00008A                  00000004             (4/7)28+R4       EQU   4
00008A                  00000005             (4/8)29+R5       EQU   5
00008A                  00000006             (4/9)30+R6       EQU   6
00008A                  00000007            (4/10)31+R7       EQU   7
00008A                  00000008            (4/11)32+R8       EQU   8
00008A                  00000009            (4/12)33+R9       EQU   9
00008A                  0000000A            (4/13)34+R10      EQU   10
00008A                  0000000B            (4/14)35+R11      EQU   11
00008A                  0000000C            (4/15)36+R12      EQU   12
00008A                  0000000D            (4/16)37+R13      EQU   13
00008A                  0000000E            (4/17)38+R14      EQU   14
00008A                  0000000F            (4/18)39+R15      EQU   15
00008A                                       (1/6)41          END 

Symbol Table Listing

 SYM=MEL      LOC=FFFFFFFF LEN=FFFFFFFF ESD=0000 TYPE=UND  XREF=
 SYM=R0       LOC=00000000 LEN=00000001 ESD=0000 TYPE=ABS  XREF=24 
 SYM=R10      LOC=0000000A LEN=00000001 ESD=0000 TYPE=ABS  XREF=34 15 
 SYM=R1       LOC=00000001 LEN=00000001 ESD=0000 TYPE=ABS  XREF=25 
 SYM=R11      LOC=0000000B LEN=00000001 ESD=0000 TYPE=ABS  XREF=35 
 SYM=R12      LOC=0000000C LEN=00000001 ESD=0000 TYPE=ABS  XREF=36 
 SYM=R13      LOC=0000000D LEN=00000001 ESD=0000 TYPE=ABS  XREF=37 
 SYM=R14      LOC=0000000E LEN=00000001 ESD=0000 TYPE=ABS  XREF=38 
 SYM=R15      LOC=0000000F LEN=00000001 ESD=0000 TYPE=ABS  XREF=39 
 SYM=R2       LOC=00000002 LEN=00000001 ESD=0000 TYPE=ABS  XREF=26 
 SYM=R3       LOC=00000003 LEN=00000001 ESD=0000 TYPE=ABS  XREF=27 
 SYM=R4       LOC=00000004 LEN=00000001 ESD=0000 TYPE=ABS  XREF=28 
 SYM=R5       LOC=00000005 LEN=00000001 ESD=0000 TYPE=ABS  XREF=29 
 SYM=R6       LOC=00000006 LEN=00000001 ESD=0000 TYPE=ABS  XREF=30 
 SYM=R7       LOC=00000007 LEN=00000001 ESD=0000 TYPE=ABS  XREF=31 
 SYM=R8       LOC=00000008 LEN=00000001 ESD=0000 TYPE=ABS  XREF=32 
 SYM=R9       LOC=00000009 LEN=00000001 ESD=0000 TYPE=ABS  XREF=33 
 SYM=SAMPLE3  LOC=00000000 LEN=00000090 ESD=0001 TYPE=CST  XREF=2 12 

Literal Table Listing

 
AZ390I total mnote warnings = 0
AZ390I total mnote errors   = 0
AZ390I max   mnote level    = 0
AZ390I total mz390 errors   = 0
AZ390I total az390 errors   = 0
15:40:36 SAMPLE3   MZ390 ENDED   RC= 0 SEC= 0 MEM(MB)= 94 IO=371

**Comment by dsh33782** [comment]
I found and fixed this error in az390.java.  It will be included in z390_v1707 zip release.
The problem appears to have been introduced when IIHF and IILF instructions were changed to support relocatible values in 32 bit I2 field within instruction.  The calc_exp() function used to process the I2 operand was not checking for undefined symbol error.
