### ISSUE TITLE
Update VSE macros to resolve low storage mapping changes made since 2007 

### ISSUE THREAD

**Issue by dsh33782** [z390development/z390#244]
The demo program BAT\RUNVSEDEMOS.BAT fails with base addressing error,  Something has changed since 2007 and
the VSE macros need to be updated to reflect those changes.

**Comment by abekornelis** [comment]
@dsh33782 Please re-test to verify whether problem persists.

**Comment by dsh33782** [comment]
Push has been submitted to fix error in bat\RUNVSEDEMOS.BAT.  All 3 vse demos now run correctly on Windows as well as Linux where John fixed the original assembly error that was causing base address error.
