### ISSUE TITLE
Missing macro VCDTD.MAC

### ISSUE THREAD

**Issue by jyganci** [z390development/z390#257]
When attempting to assemle z390_v1707.zip version of linklib/REPRO.MLC, I got an assembly error due to missing macro VCDTD. There are macros VCDTD1.MAC and VCDTD2.MAC but no VCDTD.MAC (which would invoke the appropriate VCDTDx.MAC).

**Comment by zarf99999** [comment]
It was never intended for REPRO.MLC to be assembled
However, John is right and therefore I have created the hybrid front-end to VCDTD and sent it to John, this will be shipped with the next z390 release
Melvyn

**Comment by abekornelis** [comment]
@abekornelis Please pick this up with Melvyn

**Comment by zarf99999** [comment]
Hi Guys,

Is there still an issue with this ?

I responded that it would be fixed in the next release

Regards and stay safe,

Melvyn.
  ----- Original Message -----

**Comment by adelosa** [comment]
@zarf99999 This is still an issue based on the current source in GitHub (here)! 
I'm working on #313 and #314 and have added a linklib build and it fails to build REPRO with the VCDTD macro missing. 

@zarf99999 - why should REPRO not be built?? Sorry if that is a stupid question. 

If you post the patch details here, I will put the pull request together and add it to the automated build process.

On a related topic - we have 2 versions of VSAM in the source. For the automated build, do we build both V1 and V2 as separate builds and when we eventually create a distribution, what version do we use?

**Comment by abekornelis** [comment]
Anthony,

the Repro program, the VCDTD macro and a bunch of related updates from
Melvyn were intended to pass through my hands into the repository.

If you fix it directly with Melvyn, that's okay too.
I'll be busy for a while completing the Dave Kienow changes.

It seems I've broken something during the manual merge process :-(

On the 2 zVSAM versions: we build a single jar that contains dual code.
During initialization an option can be specified to select the version you
want to be active.

Kind regards,
Abe
===


Op 06/07/2021 om 12:35 schreef Anthony Delosa:

**Comment by adelosa** [comment]
Thanks @abekornelis -- I'll chase this up directly with @zarf99999..
Melvyn - are you able to send me the changes required for this item? I'll get the changes added to the repo.

**Comment by dsh33782** [comment]
As of alpha2 release, VCDT.MAC has been added to mac dir, and REPRO has been built in linklib so I'm closing this issue.
