### ISSUE TITLE
Inconsistency between VCLR DSECT field offsets and storage created by DEFINE macro

### ISSUE THREAD

**Issue by jyganci** [z390development/z390#258]
When attempting to test zVSAM V1 using z390_v1707.zip, I noticed an inconsistency between the offsets for three VCLR fields in the VCLR DSECT and the actual data generated by the DEFINE macro. Specifically, when running vsam1/demo/DEMOCAT.BAT, the generated VCDT shows the VCLR fields just after field VCLRVX0A in the order and offset
```
02C  VCLRCI
030  VCLRAIXN
034  VCLRAIXA
```
However, the DSECT (and vz390.java) has offsets
```
02C  VCLRAIXN
030  VCLRAIXA
034  VCLRCI
```
Luckily, these three fields do not appear to be referenced by and zVSAM V1 code.

The inconsistency must be resolved. Emails with Melvyn Maltz indicate the DEFINE offsets are the correct ones, so the DSECT and vz390.java code should be changed to match the DEFINE offsets.

**Comment by zarf99999** [comment]
I don't understand why this MUST be corrected if the fields are not referenced
I have corrected VCDTD1 and sent a copy to John
This correction will be included in the next z390 release
Melvyn

**Comment by abekornelis** [comment]
@abekornelis please pick this up with Melvyn and John to resolve and fix.

**Comment by zarf99999** [comment]
Hi Guys,

Like #257, it will be fixed in the next release

Melvyn.
  ----- Original Message -----

**Comment by dsh33782** [comment]
As of alpha2, the mac\VCDT1.MAC has been updated.
