### ISSUE TITLE
ASSIST demo DEMOAST1.MLC incorrectly calculates prime numbers less than 100

### ISSUE THREAD

**Issue by jyganci** [z390development/z390#281]
When testing the new bash script runassist (RUNASSIST.BAT), it was discovered that the output of the program assist/demo/DEMOAST1 was incorrect due to a logic error in determining whether a number is prime.

Also discovered that the ASSIST.BAT file was accidentally deleted from z390/bat. It will be added back.

**Comment by jyganci** [comment]
The #281 DEMOAST1.MLC in the repository looks okay to me, ASSIST.BAT is
back in the bat directory.

Looked at the source again. It does print out 1. Ugh! Easily fixed -- remove the
 print statement.

Is this the reason the issue was reopened?

**Comment by jyganci** [comment]
Abe,

Looked at the source. It does print out 1. Ugh! Is that the problem? Easily
fixed -- remove the print statement.

Regards,

Regards,

John Ganci

**Comment by abekornelis** [comment]
John,

I'm sorry - I thought I had closed the issue by accident.
That's why I reopened it - I guess I should have double-checked first :-(

If the issue is fixed it should be closed.

Kind regards,
Abe
===


Op 06/06/2021 om 14:53 schreef John Ganci:

**Comment by jyganci** [comment]
Abe,

I'll use this as an excuse to not print the number 1 in the list of primes.
Pull request to follow.

Regards,

John Ganci
