### ISSUE TITLE
Demo program DEMOM8Q1 seems to be gone

### ISSUE THREAD

**Issue by abekornelis** [z390development/z390#293]
Demo program demo/DEMOM8Q1.ZSM is  not in the repository - but demo/DEMOM8Q1.MLC is.
Could it be the .ZSM has been inadvertently dropped, and only the generated .MLC has been retained?

If yes, we should dig up the original .ZSM and put it back, then delete the generated .MLC from the repo and it to the .ignore file

**Comment by dsh33782** [comment]
The program demo\DEMOM8Q1,MLC is the original source MLC program written in Sept. 2005 to solve the 8 queens chess problem which is "How many ways can you place 8 queens on a chess board such that none are attacking each other".

I did find the program DEMOM8Q1.ZSM which is a modified source version of the original above without any macro labels or branch statements.  It was written in 2008 which requires translation using ZSTRMAC.MLC to produce HLASM compatible code:

*********************************************************************
* Copyright 2005 Automated Software Tools Corporation               *
* This source code is part of z390 assembler/emulator package       *
* The z390 package is distributed under GNU general public license  *
* Author - Don Higgins                                              *
* Date   - 09/30/05                                                 *
*********************************************************************
* 09/04/08 RPI 902 convert to ZSTRMAC structured code
*********************************************************************
         TITLE 'DEMOM8Q1.MLC - 8 QUEEENS CHESS PROBLEM SOLUTION'
         MACRO
         M8Q
         GBLA  &N,&X(8)
         GBLB  &COL(8),&UP(15),&DOWN(15)
         LCLA  &H
         :&H   SETA  1
         AIF   (&N EQ 0)
               :&N SETA  1
         AEND
         AWHILE (&H LE 8)
             AIF (&COL(&H) EQ 0)
                 AIF (&UP(&N-&H+8) EQ 0)
                     AIF (&DOWN(&N+&H-1) EQ 0)
                         :&X(&N)         SETA &H
                         :&COL(&H)       SETB 1
                         :&UP(&N-&H+8)   SETB 1
                         :&DOWN(&N+&H-1) SETB 1
                         :&N SETA &N+1
                         AIF   (&N GT 8)
                             MNOTE 'SOLUTION &X(1) &X(2) &X(3) &X(4) &XX
               (5) &X(6) &X(7) &X(8)'
                         AELSE
                             M8Q
                         AEND
                         :&N SETA  &N-1
                         :&DOWN(&N+&H-1) SETB 0
                         :&UP(&N-&H+8)   SETB 0
                         :&COL(&H)       SETB 0
                     AEND
                 AEND
             AEND
             :&H SETA  &H+1
         AEND
         MEND
         M8Q
         END

I recommend including both versions using a different name along with documentation.

**Comment by dsh33782** [comment]
Upon further research, The above structured macro assembler program DEMOM81.ZSM will assemble without errors using the mz390.java macro processor via bat\ASM.BAT DEMOM8Q1.ZSM command.  All the structured macro support implemented in the ZSTRMAC.MLC translator has been added to the mz390.java macro processor.  The only reason to use the ZSTRMAC.MLC translator would be to convert structured macro source programs to BAL for assembly using HLASM assembler.

I propose to replace the original demo\DEMOM8Q1.MLC with the newer more structured version above which has no macro labels or branch statements in it.  Both versions produce the same solution as PRN output. 

I recommend using the same newer source program as rt test input to the ZSTRMAC.MLC translator to verify the translated version produces the same solution.

The documentation on z390 structured macro extensions including ZSTRMAC.MLC translator are currently located here:

http://www.z390.org/z390_ZSTRMAC_Structured_Macro_Support.htm
