### ISSUE TITLE
ASSIST XHEXI instruction does not behave as documented in the ASSIST User's Manual

### ISSUE THREAD

**Issue by jyganci** [z390development/z390#305]
When examining the z390 implementation of the ASSIST instruction XHEXI, it was noticed that it does not exactly follow the ASSIST User's Manual documentation.

The documentation follows.

>         XHEXI REGISTER,ADDRESS
>
>1. Beginning at the location ADDRESS, memory is scanned until the first non-blank character is found.
>2. If the first character found is anything bu a legal hexadecimal character (0-9,A-F), the condition code is set to 3 (overflow) and this address is placed in register 1. If REGISTER is anything but register 1, its contents remain unchanged.
>3. One to eight hexadecimal characters are scanned, the number converted to hexadecimal, and the result is placed in REGISTER. The value placed in the register is internal hexadecimal with leading zeros included and the number is right justified.
>4. Register 1 is set to the address of the first non-hexadecimal character. With this in mind, the user should not code register 1 as REGISTER. This allows you to scan across the card for any number of character strings. The strings should be separated by blanks. The end of the string could be flagged with any non-hexadecimal character and a test could be made after a Branch Overflow (see sample program).
>5. If more than eight hexadecimal characters are found, register 1 is set to the address of the ninth. This allows the user to scan across long strings of numbers.

Z390 HEXI violates 2. It does not set register 1 as indicated.

Z390 HEXI violates 3. (1) It scans hexadecimal characters until a non-hexadecimal character is found, so it could potentially scan more than eight hexadecimal characters. (2) It sets condition code 0.

Z390 HEXI violates 5 because it violates 3.

Comment: the ASSIST XHEXI is flawed because it does not set a condition code when a string is successfully converted. If the condition code were 3 before the XHEXI instruction and it successfully converts a string to hexadecimal, the condition code will still be 3, indicating that the first non-blank is not a hexadecimal character. Because of the flaw, a user must ensure that the condition code is not 3 before issuing XHEXI.

The z390 XHEXI could fix this flaw, but if it should behave as the documentation specifies, it should also have the flaw.

**Comment by adelosa** [comment]
Fixed by PR #331. Closing
