### ISSUE TITLE
Doc build failing on git push to gh-pages

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#307]
See https://github.com/mkdocs/mkdocs/issues/2370

It seems that an error related to the mkdocs deploy command.  Error was introduced in the latest version of mkdocs. v1.2 has issue. Will be resolved by v1.2.1. 
Can force older version or wait for new version to be released.

**Comment by abekornelis** [comment]
@adelosa do we have an indication of time involved in waiting for next version?

**Comment by adelosa** [comment]
The new version has been released already (1.2.1). Latest build on z390 worked as expected. Closing
