### ISSUE TITLE
RPI 0692: IDCAMS Add initial LDS support

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#31]
Raised by Don Higgins 2007/09/10
Add initial LDS support with new user option CONTROLINTERVALSIZE= on DEFINE CLUSTER to support reading fixed length records in fixed block format. Note z390 VSAM default is to not use CI or CA structures to avoid wasted space and overhead of blocking for random access. See RPI 693 for planned caching to address sequential access performance.

**Comment by z390org** [comment]
Requires DIV support which we do not yet envision as we do not even have a virtual memory model yet.
