### ISSUE TITLE
Option NOPC surpresses errors in assembler

### ISSUE THREAD

**Issue by dsh33782** [z390development/z390#318]
Melvyn reported this error which can be avoided by using option NOPC.
I'll work on cut down sample to attach.

**Comment by dsh33782** [comment]
Problem isolated to program GBL0602 assembled with default PC.
FID 1  GBL0602 macro call at line 377:           MODCB ACB=IHAACB,MACRF=(ADR,DIR,KEY,SEQ,OUT)
FID 10 MODCD calls ZMODCB at line 119      ZMODCB &ACB,ACBMACR2-IHAACB,B'&ZGENMACF2',1
FID  9  ZMODCB error 217 on line 63              &ADDR    SETC  '&SOURCE'(4,K'&SOURCE-4)

The sequence is that &SOURCE is passed as B'000000' string to ZMODCB.
In PC mode, the B'000000' self defining term is pushed on stack as numeric 0.
The failing SETC statement ends up with offset 4 and length of -3 on numberic 0 instead of B'000000' .

With option NOPC, the stack ends up with B'000000' which SETC then calculates ok as '0000' with value 0.

I will be testing change to mz390 to not convert sdts during push to stack.  But it may be a few days as we have company.

**Comment by adelosa** [comment]
@dsh33782 Can we close this one.. Looks like a change was merged to fix it??

**Comment by dsh33782** [comment]
The mz390.java macro assembler has been changed to not replace self defining terms with numeric values as it caused macro code checking for SDT string values to fail.
