### ISSUE TITLE
QSAM get recfm=vt not setting LLLL correctly for LBI large block

### ISSUE THREAD

**Issue by dsh33782** [z390development/z390#321]
Bug identified in sz390.java and will be fixed along with update to qsam directory regression tests.

**Comment by dsh33782** [comment]
qsam tests updated with new CPYVT1.MLC and CPYVT1L.MLC using ascii test with multiple records from 1 to 26 albhabetic characters.  Each program displays trace of records with LLLL prefix for LBI and non LBI modes.

Copy send to Melvyn for review while I finish work on similar BSAM test addition using write/read vs put/get.

**Comment by adelosa** [comment]
@dsh33782 Will this item be fixed by #322 when it gets merged?

**Comment by dsh33782** [comment]
Anthony

 

Yes, the latest QSAM tests do verify that RECFM=VT works correctly.

 

Don Higgins

 ***@***.***> ***@***.***

 <http://www.don-higgins.net/> www.donhiggins.org

**Comment by dsh33782** [comment]
Latest QSAM tests verify RECFM=VT issue has been fixed.
