### ISSUE TITLE
Remove Perl reference in sz390.java

### ISSUE THREAD

**Issue by jyganci** [z390development/z390#337]
When the addition of bash scripts to replace the use of Perl was done, all changes to z390 required to support the bash scripts were concentrated in tz390.java and z390.java. Some time after the initial bash-related commits were done, another Perl reference (to cmd.pl) was found in sz390.java. A fix was done outside of git and tested. Alas, for some reason it was forgotten. Time to get it in now.

**Comment by dsh33782** [comment]
John said this fix is already in 1.8.00 so I removed it from 1.8.01 at his request.

**Comment by adelosa** [comment]
So if this is fixed already, can we close this issue - @jyganci?

**Comment by jyganci** [comment]
Anthony, all

It's in the beta. Seems to me that it's okay to close the issue.

**Comment by jyganci** [comment]
Why hasn't this issue been closed?

**Comment by dsh33782** [comment]
John

 

I think it should be closed.

 

Don Higgins

 ***@***.***> ***@***.***

www.don-higgins.net

**Comment by jyganci** [comment]
Fix is already in v1.8.0 rc1. Okay to close.
