### ISSUE TITLE
RPI 0736: Support for multiple opcode tables

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#36]
Raised by Abe Kornelis 2007/11/10
Add option to support different opcode tables for assembler and emulator since some of the older opcodes have been reused but there are old programs that use the old opcodes such as the vector facility. For efficiency only one special opcode table can be used by the emulator at a time. There would be another general opcode table that could be used to assemble programs which do not use any obsolete opcodes and could be run with any special opcode table.

**Comment by z390org** [comment]
Has been implemented.
