### ISSUE TITLE
z390 version as determined by relver.bat returns incorrect value from git repositry

### ISSUE THREAD

**Issue by abekornelis** [z390development/z390#365]
Running the relver.bat procedure git returns version number v1.7.06-147-g34939cd

This should be V1.8.something

Where in git is this to be adjusted?

**Comment by adelosa** [comment]
This is because you have not pulled the tags from the upstream repo.
Tags are not automatically pulled and the version process relies on tags hence the issue.

To fix on your forked copy:

    git remote add upstream https://github.com/z390development/z390.git
    git fetch upstream --tags

After you do this, let me know if you still think this is an issue..

**Comment by abekornelis** [comment]
Anthony, thanks. Problem seems to be resolved.
