### ISSUE TITLE
Test program rt\mlc\TBRCTX hangs looping

### ISSUE THREAD

**Issue by abekornelis** [z390development/z390#370]
The test program  rt\mlc\TBRCTX ends up looping:
Program was loaded at hex 8000, displays two WTO messages (only the second is shown in the trace below):
 800080C0 2 0A23         SVC   I1=23 WTO R1=ADDR(AL2(LEN),AL2(FLAGS),C'MSG')
After BRCTH loop; R2=0000000000000003  R3=0000000000000000
 800080C2 2 07FA         BR    RA(80008050)=B9090022 SGR
 80008050 2 B9090022     SGR   R2=0000000000000003 R2=0000000000000003
 80008054 0 B9090033     SGR   R3=0000000000000000 R3=0000000000000000
 80008058 0 C03800000001 IIHF  R3=0000000000000000 I2=00000001
 8000805E 0 A72B0001     AGHI  R2=0000000000000000 I2=0001
 80008062 2 A737FFFE     BRCTG R3=00000000 S2(0000805E)=A72B0001 AGHI
 8000805E 2 A72B0001     AGHI  R2=0000000000000001 I2=0001
 80008062 2 A737FFFE     BRCTG R3=FFFFFFFF S2(0000805E)=A72B0001 AGHI
 8000805E 2 A72B0001     AGHI  R2=0000000000000002 I2=0001
 80008062 2 A737FFFE     BRCTG R3=FFFFFFFE S2(0000805E)=A72B0001 AGHI
 8000805E 2 A72B0001     AGHI  R2=0000000000000003 I2=0001
 80008062 2 A737FFFE     BRCTG R3=FFFFFFFD S2(0000805E)=A72B0001 AGHI

so the programs loops at offset 5E/62 which is associated with the loop at label BRCTG_1
In the trace we can see the counter decrementing with each loop.
Is the starting value correct? Is this intentional? 
I guess after (quite) a while the loop will terminate anyway.
Is it really needed to go over 2 Billion iterations before the counter reaches zero?
Please restrict test to a reasonable number of iterations.

**Comment by dsh33782** [comment]
Abe

I didn't write that code and I don't know who did because there are no update comments.
I found the bug and fixed it by replacing IIHF with LG before BRCTG loop.
Now it runs quickly.
[TBRCTX.TXT](https://github.com/z390development/z390/files/8238595/TBRCTX.TXT)

**Comment by abekornelis** [comment]
Don, sorry for assuming that you would have been the author. And thanks for supplying the fix.
I'm including the solution in pull request #364

**Comment by jyganci** [comment]
I'm the author of TBRCTX. The BRCTG_1 loop
```
         SGR   R2,R2               Count iterations
         SGR   R3,R3               Initialize all 64 bits
         IIHF  R3,1                Loop count
BRCTG_1  DS    0H
         AGHI  R2,1                Count iterations (64-bit counter)
         BRCTG R3,BRCTG_1          Loop
```
is correct. It just has a very large counter -- 2^32. A bit extreme, yes, but done intentionally. On my PC TBRCTX runs for about four and a half minutes. Sample run:
```
$ bash/asmlg rt/mlc/TBRCTX notime
07:46:47 TBRCTX    MZ390 START USING z390 v1.8.0 ON J2SE 1.8.0_201 03/26/22
07:46:47 TBRCTX    MZ390 ENDED   RC= 0 SEC= 0 MEM(MB)= 74 IO=843
07:46:47 TBRCTX    LZ390 START USING z390 v1.8.0 ON J2SE 1.8.0_201 03/26/22
07:46:47 TBRCTX    LZ390 ENDED   RC= 0 SEC= 0 MEM(MB)= 13 IO=74
07:46:48 TBRCTX    EZ390 START USING z390 v1.8.0 ON J2SE 1.8.0_201 03/26/22
After BRCT  loop; R2=0000000000000003  R3=0000000000000000
After BRCTH loop; R2=0000000000000003  R3=0000000000000000
After BRCTG loop; R2=0000000100000000  R3=0000000000000000
07:51:13 TBRCTX    EZ390 ENDED   RC= 0 SEC=265 MEM(MB)= 27 IO=25 INS=8589934672
```
I should've put a comment in the source and issued a WTO before that loop began. Having one regression test run for four and a half minutes is too much time, I guess. Sorry about that.

**Comment by abekornelis** [comment]
was fixed some time ago

**Comment by abekornelis** [comment]
That is, we reduced the initial value fr the countdown to a very low value. What would be a reasonable value? Do you have a suggestion, John?

**Comment by jyganci** [comment]
Since BRCTG uses a 64-bit counter, I chose to initialize the counter to a
value greater than 2^31 - 1. Any such value will increase the run time
significantly. Setting the counter to 3 is fine if a value less than 2^31
is desired.

**Comment by abekornelis** [comment]
Crossing the border of 2**32 is a valid and important test.
Yet, to execute that test do we really need to count down to zero?
Would it be an option to have a loop to decrement from a few above to a few below the boundary?
Then validate that the loop was executed as many times as expected?

**Comment by jyganci** [comment]
The original counter value, 2^32, is 1 bit above. On the first iteration,
the counter becomes X'FFFFFFFF', which is 2^32 - 1. It will take 2^31
additional iterations to get the counter down to X'7FFFFFFF' = 2^31 - 1
(dropping 1 bit below). Based on my run with 2^32, this will take about 2
minutes.  So, just to do the minimum "few above, few below" of 1,1 will
take 2+ minutes.

That's still a lot of time for one regression test.

**Comment by abekornelis** [comment]
Yes, that's why I'm looking to take a shortcut. Counting down from 2**32-1 to 1 adds very little value.
So can we make it count down from 2**+1 to 2**32-1 then abort the loop?
Then test counting down from 1 to zero and from zero to -1.
I think these are the important test cases. Am I mising any?

**Comment by jyganci** [comment]
I never said count down from 2^32 - 1 to 1. I said count down from 2^32 - 1
to 2^31 - 1. It appears that you did not read my response.

I do not understand what you are suggesting.

My suggestion.

 Two tests.

 The counter (Rx in BRCTG Rx,Label) is a 64-bit positive number.

 In what follows,  "x-bit positive number" is shorthand for "64-bit
positive number with high order 64-x bits zero".

Test 1. Counter crosses from 33-bit positive number 32-bit positive number
that is a negative 31-bit fullword value.

Set GR3 to 2^32 + 1 (X'00000001',X'00000001').. Set R5 to 5.
Loop1:
              BCT   R5,Next1
              B      Loop1E
Next1:    BRCTG  R3,Loop1
Loop1E:
              WTO something that indicates test is successful.

Test 2. Counter crosses from 32-bit positive number that is a negative
31-bit fullword to a positive 31-bit fullword.

Set GR3 to 2^31 + 1 (X'00000000',X'80000001'). Set R5 to 5. Use same code
as above.

Once again we are wasting time dealing with a triviality. My feeling right
now is to leave the code as is. If you feel differently, then by all means
change the code.

**Comment by abekornelis** [comment]
I'll be happy to follow your advice: I'll leave the code as is. And will close this issue. Thanks for sharing your thoughts.
