### ISSUE TITLE
Need a bit of help

### ISSUE THREAD

**Issue by vmdave9** [z390development/z390#379]
Hello, all.
I am attempting to run z390 here on my Linux laptop (openSUSE Tumbleweed). I do have java installed:
dave@dave-ThinkPad-T480:~/z390/bash$ java -version
java version "17.0.2" 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)
but when I try to run the bash script "runasmdemos" I get this error:
dave@dave-ThinkPad-T480:~/z390/bash$ ./runasmdemos
Error: Could not find or load main class mz390
Caused by: java.lang.ClassNotFoundException: mz390
asmlg: mz390 error; mz390 rc=1; see errors in demo/HELLO.BAL file and on console
dave@dave-ThinkPad-T480:~/z390/bash$ 
I am not a java person, so I would like to buy a clue on how to fix this error.
Many thanks.
DJ

**Comment by vmdave9** [comment]
Never mind....just discovered you need to run the build.sh script first.
DJ

**Comment by abekornelis** [comment]
Dave,

thanks for reaching out. Welcome to the z390 community.
I see you found the solution to your issue - that's good.

Would you please consider subscribing to https://groups.google.com/g/z390/
You will be aware of the latest z390 news, plus you can post any questions you may run into ...

Kind regards,
Abe Kornelis
========
