### ISSUE TITLE
ED (edit) instruction handles alternate signs incorrectly

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#434]
Reported by Martin Ward (martin@gkc.org.uk) on z390development Google group.

According to the latest POP, Page 8-2:

"Alternate sign codes are also recognized as valid in the sign position: 1010, 1110, and 1111 are alternate codes for plus, and 1011 is an alternate code for minus. Alternate sign codes are accepted for any decimal source operand, but are not generated..."

This means that an edit with mask X'4020212060' and source X'300A' should treat the source as positive and generate C' 300 ' with the condition code set to 2.

z390 treats the source as negative and returns X' 300-' with the condition code set to 1.

This code in exec_ed_edmk in src/pz390.java:

```java
if (source_sign > 9) {
    if (source_sign == 0xc || source_sign >= 0xe) {
        sig_digit = false;
    } else if (psw_cc == psw_cc_high) {
        psw_cc = psw_cc_low;
    }
}
```

should be something like this:

```java
if (source_sign > 9) {
    if (source_sign =! 0xd && source_sign != 0xb) {
        sig_digit = false;
    } else if (psw_cc == psw_cc_high) {
        psw_cc = psw_cc_low;
    }
}
```

**Comment by jyganci** [comment]
Fixed by merged PR #480
