### ISSUE TITLE
Changes to bash scripts that incorporate corresponding changes to bat files

### ISSUE THREAD

**Issue by jyganci** [z390development/z390#443]
Issues #359, #363, and #374 modified some Windows bat files to better handle error conditions. The corresponding bash scripts should also be modified.

**Comment by adelosa** [comment]
@jyganci Is this linked to a pull request you are working on?

**Comment by jyganci** [comment]
Long time ago. I believe this is already resolved. See
https://github.com/z390development/z390/pull/445
