### ISSUE TITLE
Questions concerning non-printable characters in PRN files

### ISSUE THREAD

**Issue by jyganci** [z390development/z390#454]
Mainframe HLASM SYSPRINT output shows non-printable characters as periods. For example, TSO edit for TA01B shows
```
-CAUTION- Data contains invalid (non-display) characters. Use command
          ===> FIND P'.' to position cursor to these                 
TA01B    CSECT 
ECFFC4444CECCE4444444
310120000325330000000
---------------------
         DC    C'A B'
444444444CC4444C7C0C7
0000000004300003D112D
---------------------
         END 
444444444CDC444444444
000000000554000000000
---------------------
```
The character between the A and the B, shown as space in TSO edit, is X'01'. When assembled, the return code is 0 and the SYSPRINT output shows the non-printable X'01' as a period.

```
  Loc  Object Code    Addr1 Addr2  Stmt   Source Statement 
000000                00000 00003     1 TA01B    CSECT       
000000 C101C2                         2          DC    C'A.B'
                                      3          END         
```
Using z390 to assemble TA01B yields
```
Assembler Listing
000000                                        (1/1)1 TA01B    CSECT 
000000 C101C2                                 (1/2)2          DC    C'AB'
000003                                        (1/3)3          END 
```
The error message
```
MZ390E error 138         (1/2)2 invalid ascii source line 2 in /<path>/TA01B.MLC
```
appears and the assembly ends with RC 12. Note the non-printable character between the A and the B.

If you look at Pull Request #444, you will see a sample program, TX2C1.MLC, that creates DC statements. using X2C. Modifying it to test X2C('C101C2' produces the same DC statement as above but the assembly ends with RC 0.
```
Assembler Listing
000000                                        (1/1)1 TX2C1    CSECT 
000000                                       (1/17)2 *        Test X2C with X'C101C2'
000000 C101C2                                (1/19)3          DC    C'AB'
000003                                       (1/20)4          END 
```
Questions:
1. Should z390 allow non-ASCII in a source  file?
2. Should z390 replace non-printable characters in PRN files with periods, as is done on the mainframe?

**Comment by abekornelis** [comment]
Whether or not valid ASCII input text should be enforced is determined by the CHKSRC parameter. From the current doco:

> Check input source files as follows:
> 0 - no checking
> 1 - check MLC or BAL input source files for any  non-ASCII characters and issue error
> 2 - check MLC, MAC, CPY, and BAL input source files for any non-ASCII characters and issue error.
> 3 - also check for out of sequence characters in 73-80 or any non-blank characters beyond 80 and issue error.
> Note this should detect any EBCDIC literal character strings containing non-ASCII characters such as binary 0 byte which must be changed to hex X'00' type strings for portability.

**Comment by jyganci** [comment]
Answer accepted. Closing issue.
