### ISSUE TITLE
ZC390LIB NOT FOUND

### ISSUE THREAD

**Issue by Maiz2005** [z390development/z390#461]
When i tried to compile a Cobol program display this message:

11:28:19 Hello1    ZC390 START USING z390 v1.8.1 ON J2SE 1.8.0_201 12/22/22
11:28:19 Hello1    ZC390 ENDED   RC= 0 SEC= 0 MEM(MB)=  7 IO=2
11:28:19 Hello1    MZ390 START USING z390 v1.8.1 ON J2SE 1.8.0_201 12/22/22
AZ390E error  29       (9/75)11            SAVE  (14,12)
AZ390E error  29      (9/124)29            LOAD  EP=ZC390LIB
AZ390E error  29      (9/127)32            WTO 'ZC390LIB NOT FOUND'
AZ390E error  29      (9/141)46            WTO 'ZC390LIB ZCVT VERIFY ERROR'

**Comment by adelosa** [comment]
I'll try to assist you with getting started with z390.
This error is basically saying that the zc390lib, which is a library used by cobol code was not found.

If you use the z390 package (which is the recommended approach), it is packed with everything you need to run, including this library and you should not get this issue.
See the docs on getting started including installing the z390 package.
https://z390development.github.io/z390/getting_started/install/

Then try the COBOL quickstart to ensure z390 is installed correctly.
https://z390development.github.io/z390/getting_started/quickstart/#hello-zcobol

Please follow these instructions and let me know how you go.

If you want to use z390 from source, then review the following page in the guide.
https://z390development.github.io/z390/contributing/contribute_code/

**Comment by Maiz2005** [comment]
Thanks for the respond.

I have all the steps done and in assembler I can compile and execute, only in cobol not.

One observation, in the example of the cobol HELLO program, a file with an MLC extension cannot be compiled because the CBLCLG.BAT file requires a CBL file, the example is wrong.

For Example:

C:\z390\Progs>cblclg hello1
.
the CBLCLG.BAT procedure is intended to compile, link, and execute a single cobol program
.
Hit Enter for more help or suppply name of cbl file to compile, link, and execute:

TIA

**Comment by adelosa** [comment]
Thanks for picking up that issue with the documentation..
It should say that that COBOL program filename is `HELLO.CBL` not `HELLO.MLC`
If you change the filename, the COBOL compile should work.
Let me know how you go after changing the file name.

**Comment by adelosa** [comment]
I am going to assume you have resolved your issue. If possible can you please confirm this by responding here. Thanks
