### ISSUE TITLE
bug in FD.mac

### ISSUE THREAD

**Issue by abekornelis** [z390development/z390#482]
Mail from John Hennesy, dated 2023-04-17 10:36:

I got an error testing and i tracked it down to FD.mac,
When it is storing values to an array it is using &parm_ix when it should be using &file_ix. This affects variables &file_blksi2, & file_blksi1, &file_block_recs, &file_lrecl2, &file_lrecl1, &file_depending.

Effectively, &parm_ix points to a position in the syslist and &file_ix points at the relative position of a file amongst any other files.

**Comment by abekornelis** [comment]
We'll have to look into the macro and double-check John's findings. Assuming John is correct, we should fix the issue.

**Comment by jyganci** [comment]
Can we get a simple sample COBOL source program that illustrates the problem?

Next comment agrees with John Hennesy's comments. Still would like a simple sample COBOL program to use to verify the changes and add to the test suite.

**Comment by jyganci** [comment]
Agree with John Hennesy that FD.MAC appears to be incorrectly accessing &FILE_xxx arrays.
1. FD.MAC line 30 "ZC_FILE_FIND &FILE" sets GBLA &FILE_IX to appropriate index into the &FILE_xxx arrays. See ZC_WS.CPY in the cpy directory.
2. FD.MAC line 63 correctly uses &FILE_IX to set &FILE_RECORD array entry.
3. FD.MAC lines 70, 73, 74, 81, 105, 108, 109, and 120 use &PARM_IX to set &FILE_xxx array values for xxx =  BLKSI2, BLKSI1, BLKSI2, BLOCK_RECS, LRECL2, LRECL1, LRECL2, and DEPENDING, respectively.  All of these should be using &FILE_IX as the array index as john Hennessy stated.

**Comment by abekornelis** [comment]
John, I have asked John Hennesy to provide a simple sample program that exhibits the symptoms.

**Comment by jyganci** [comment]
I'll have a new branch in my clone ready for testing.

**Comment by jyganci** [comment]
Fixed in PR #494
