### ISSUE TITLE
Remove hard-coded file names in source modules used in regression tests

### ISSUE THREAD

**Issue by jyganci** [z390development/z390#520]
COBOL source demo/COPYFILE.CBL, rt/test/TESTCMD3,MLC and rt/test/TESTCMD4.MLC contain hard-coded names for external files used for testing. This causes issues in the Groovy regression test scripts that use thise programs. Changes required:
1. Change COPYFILE.CBL to use DDNAMEs INFILE and OUTFILE instead of the hard-coded names.
2. Change bash/runcbldemos and bat/RUNCBLDEMOS.BAT to set environment varibles INFILE, OUTFILE containing these names.
3. Change TESTCMD3.MLC and TESTCMD4.MLC to no longer determine whether Windows or Linux/MacOS to determine test file names. Instead, get file names from environment variables.
4. Change bash/runcmdproc and bat/RUNCMDPROC.BAT to set the appropriate environment variables.
5. Modify regression test files RunCblDemos.groovy and RunCmdProc.groovy to mimic the bash,bat changes described in 2 and 4.

**Comment by adelosa** [comment]
Thanks for doing this work John. The changes you are proposing look fine to me. 
I have reviewed your groovy test scripts and they are perfect... and it removes the complexity of dynamically modifying the scripts that was there before. 

Can you create a pull request with these changes and then I can run them locally and review the actual code here on GitHub?

I'll have a look at the Gradle Deprecation warning message and suggest a fix once you get your pull request completed.
https://docs.gradle.org/current/userguide/upgrading_version_8.html#test_framework_implementation_dependencies
Looks like it can be fixed easily by adding a dependency to the JUnit test library.

I'll rebase my #519 PR on top of this change once it's merged to main.
Thanks again @jyganci !

**Comment by jyganci** [comment]
All,

Pull request #521 that fixes issue #520 created. This is for the problems
reported by Anthony with regard to some Groovy scripts in the regression
test set.

Note: Even though we are probably 99% confident of the new Groovy
regression test setup, I'm still adding the old style bash and bat file
tests along with the corresponding modified Groovy scripts.

Anthony: I assigned you as reviewer.

Regards, John Ganci

**Comment by jyganci** [comment]
Fixed by PR #521
