### ISSUE TITLE
RPI 0919: Enhanced VSAMsupport

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#56]
Raised by RB/JM 2008/09/23
Add VSAMsupport for the following:
1) ACB support definition of field for STRNO=
2) SHOWCB for ACB FIELDS=(ERROR,LRECL,STRNO)
3) SHOWCB extend short field numeric values with zeros on left for compatibility.
4) MODCB support AREALEN=(reg)
4) Add support for ENDREQ macro
5) add support for LOCATE versus MVE move mode default.
6) Correct trap on null pointer during REPRO load of VSAM file.

**Comment by z390org** [comment]
We will not implement this in zVSAM V1. For zVSAM V2 this is part of the plans.
