### ISSUE TITLE
RPI 1006: Add support for missing COBOL verbs

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#67]
Raised by Don Higgins 2009/03/20
Add missing support for zcobol verbs:
1) MERGE, SEARCH
2) ENABLE, DISABLE
3) REPORT, RD, INITIATE, GENERATE, TERMINATE
4) COMMUNICATIONS, CD
5) DIRECTIVES, USE
6) REPLACE (see NIST SM208A)

**Comment by z390org** [comment]
With Don we decided to close this issue. We'll reraise new issues with separate findings as we go and proceed.
