### ISSUE TITLE
RPI 1095: Enhance linklib\ZSTRMAC.MLC to support translation of individual macros with structured code

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#80]
Raised by Unknown 2009/10/12
Correct linklib\ZSTRMAC.MLC translator tohandle translation of individual macros with structured code versus complete programs with structured open code:
1) Generate unique labels within each macro rather than unique within program.
2) Expand COPY statements within macros.

**Comment by z390org** [comment]
Don and I do not see enough added value. If you want to test a macro, please embed it in the program you're planning to write anyway...
