### ISSUE TITLE
RPI 1145: Redesign KSDS and AIX support

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#87]
Raised by Melvyn Maltz 2011/01/16
Redesign KSDS and AIX support to use full KSDS structure with single key for unique and non-unique keys in primary KSDS and variable length data segment containing pointers to base KSDS records:
1) Each KSDS entry has 2 byte prefix indicating primary or AIX type and length of key
2) Data segment contains 4 byte count of entries (1 or unique key)

**Comment by z390org** [comment]
We're not extending zVSMA V1 support. This will be part of zVSAM V2.
